<?php require 'includes/db.php';

if(!isset($_SESSION['email'])) {
    header("Location: login.php");
    exit();
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PMS - Academic Statistics</title>
    <link rel="stylesheet" href="css/essential.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="css/academicStats.css">

</head>
<body>
    <header id="header-placeholder"></header>
    
    <main>
        <div class="leftContainer">
            <a href="studentDashboard.php" class="backButton">
                <i class="fa fa-arrow-left" style="margin-right: 10px"></i>Back to Dashboard
            </a>
            <div class="profileSection">
                <img src="assets/profile.png" alt="Profile Picture" class="imageCircle">
            </div>
            <h1>John Doe</h1>
            <p>GRADE 5 (Class A)</p>
        </div>
        
        <div class="rightContainer">
            <div class="leftCards">
                <div class="dashboard-card GPA">
                    <h1 class="card-title">GPA</h1>
                    <div class="gpa-display" id="gpaDisplay">90.50</div>
                </div>
                <div class="dashboard-card ATTENDANCE">
                    <h1 class="card-title">Attendance</h1>
                    <div class="attendance-grid" id="attendanceGrid">
                        <!-- Attendance dots will be generated by JavaScript -->
                    </div>
                    <div class="attendance-legend">
                        <div class="legend-item">
                            <div class="legend-dot present"></div>
                            <span>Present</span>
                        </div>
                        <div class="legend-item">
                            <div class="legend-dot absent"></div>
                            <span>Absent</span>
                        </div>
                        <div class="legend-item">
                            <div class="legend-dot late"></div>
                            <span>Late</span>
                        </div>
                        <div class="legend-item">
                            <div class="legend-dot excused"></div>
                            <span>Excused</span>
                        </div>
                    </div>
                    <div class="appeal-badge">15 Appeal for Absence</div>
                </div>
                
                <div class="dashboard-card QUARTER">
                    <h1 class="card-title">Quarter</h1>
                    <div class="quarter-display">4th</div>
                </div>
            </div>
            
            <div class="rightCards">
                <div class="SUBJECT_GRADES">
                    <h2>Subject Grades</h2>
                    <p>Grades</p>
                    <div class="grades-chart">
                        <div class="grade-bar" style="height: 85%;" onclick="showGradeDetails('Filipino', 95)">
                            <div class="grade-value">95</div>
                            <div class="subject-label">Filipino</div>
                        </div>
                        <div class="grade-bar" style="height: 75%;" onclick="showGradeDetails('Science', 88)">
                            <div class="grade-value">88</div>
                            <div class="subject-label">Science</div>
                        </div>
                        <div class="grade-bar" style="height: 65%;" onclick="showGradeDetails('Math', 82)">
                            <div class="grade-value">82</div>
                            <div class="subject-label">Math</div>
                        </div>
                        <div class="grade-bar" style="height: 78%;" onclick="showGradeDetails('English', 90)">
                            <div class="grade-value">90</div>
                            <div class="subject-label">English</div>
                        </div>
                        <div class="grade-bar" style="height: 68%;" onclick="showGradeDetails('AP', 85)">
                            <div class="grade-value">85</div>
                            <div class="subject-label">AP</div>
                        </div>
                        <div class="grade-bar" style="height: 92%;" onclick="showGradeDetails('CP-TLE', 96)">
                            <div class="grade-value">96</div>
                            <div class="subject-label">CP-TLE</div>
                        </div>
                        <div class="grade-bar" style="height: 72%;" onclick="showGradeDetails('MAPEH', 87)">
                            <div class="grade-value">87</div>
                            <div class="subject-label">MAPEH</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    
    <footer id="footer-placeholder"></footer>
    
    <script src="js/layout-loader.js"></script>
    <script src="js/statLoader.js"></script>
</body>
</html>